### ISSUE TITLE
Album images endpoint not under '/aura/' prefix

### ISSUE THREAD

**Issue by out-of-range** [beetbox/aura#16]
In the images section there is an endpoint [/albums/(id)/images](https://auraspec.readthedocs.io/en/latest/api.html#get--albums-(id)-images), which I'm guessing is a mistake?

**Comment by sampsyo** [comment]
Absolutely; thanks for pointing that out!

**Comment by out-of-range** [comment]
No worries, though I'm not seeing the fix on readthedocs yet. Is that something that will update automatically in a couple of days or is it a manual thing?

**Comment by sampsyo** [comment]
Thanks for pointing that out; looks like the integration broke. I've set it back up again and triggered a build.

**Comment by out-of-range** [comment]
All good now :)
