### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by gryphonmyers** [beetbox/aura#20]
I didn't see any mention of this in the specification, so I'll ask: should clients be able to specify sort order? Without the ability to sort, clients may be limited in terms of user-friendly views they can render. If sort is not supported, then what order should documents be sent in?

**Comment by sampsyo** [comment]
Good question. I think we should probably add sorting—and, fortunately, JSON-API has a recommendation for how to do that:
https://jsonapi.org/format/#fetching-sorting

**Comment by gryphonmyers** [comment]
Oh nice! This looks like an elegant solution and should be straight-forward to incorporate into the spec.

**Comment by out-of-range** [comment]
Hi, what do you both think of #26 as a first draft?

**Comment by out-of-range** [comment]
I think with #28 this is 'solved', so I'll close the issue.
